'use strict';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=['首页','在线智能助理','客服助理','监控专区','服务专区','用量专区','办理专区','商机单','故障单','综合专区','投诉/查询单','系统管理','工单管理','流程管理'];const icons=['⌂','♟','◉','◉','☏','☑','','♜','☀','','▱','⚙','','◉'];$('#sidebar').innerHTML=nav.map((n,i)=>`<div class="side-item ${i===1?'active':''}"><span class="side-icon">${icons[i]}</span>${n}${i>2?'<span class="chev">⌄</span>':''}</div>`).join('');
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
const clock=()=>new Date().toLocaleString('sv-SE').slice(0,16);
const customers=[
 {number:'18938839389',city:'广州',region:'Cst广州020',location:'广东省广州市 电信',name:'张*',salutation:'张女士',avatar:'张',session:'1549160251',im:'oeKd5jjAVatZ9JeYYLASIIBJcH3g',messages:[{role:'customer',text:'你好，我想咨询本月的流量使用情况，麻烦帮我查询一下。',time:''},{role:'agent',text:'您好，我这边帮您查询到当前的流量使用情况。',time:'2024-12-11 14:34'},{role:'customer',text:'嗯嗯，那剩下了多少呢，会不会超出？',time:'2024-12-11 14:35'},{role:'agent',text:'您当前还剩余27.8GB，后续请注意不要产生额外流量。',time:'2024-12-11 14:36'}],recommendation:{time:'2024-12-11 14:36',scene:'流量争议 > 达量断网且有新订包',intro:'根据用户咨询的流量使用情况，推荐以下回复：',text:'您好，已为您查询到当前的流量使用情况。您本月已使用XX，剩余XX，如需办理流量包可以点击下方链接。'},summary:['流量使用情况查询','查询本月剩余流量及是否会超出','已告知用户当前剩余27.8GB，建议注意后续使用','如有其他问题可随时联系']},
 {number:'13310022202',city:'中山',region:'Cst中山0760',location:'广东省中山市 电信',name:'李*',salutation:'李先生',avatar:'李',session:'1549160252',im:'oeKd5jjAVatZ9JeYYLASIIBJcH4h',messages:[{role:'customer',text:'你好，我想查一下这个月的账单费用。',time:'2024-12-11 14:31'},{role:'agent',text:'您好，我现在为您核查本月账单，请稍等。',time:'2024-12-11 14:32'}],recommendation:{time:'2024-12-11 14:32',scene:'费用争议 > 账单费用核查',intro:'根据用户咨询的账单情况，推荐以下回复：',text:'您好，我这边为您核查本月账单及费用明细，请您稍等。'},summary:['账单费用查询','查询本月账单及费用明细','正在为用户核查本月账单','核查完成后向用户反馈']},
 {number:'17779293222',city:'佛山',region:'Cst佛山0757',location:'广东省佛山市 电信',name:'王*',salutation:'王女士',avatar:'王',session:'1549160253',im:'oeKd5jjAVatZ9JeYYLASIIBJcH5i',messages:[{role:'customer',text:'你好，我想咨询一下国际漫游怎么开通。',time:'2024-12-11 14:28'},{role:'agent',text:'您好，我来为您查询国际漫游开通方式。',time:'2024-12-11 14:29'}],recommendation:{time:'2024-12-11 14:29',scene:'国际漫游 > 国际漫游功能',intro:'根据用户咨询的国际漫游情况，推荐以下回复：',text:'您好，您可以通过中国电信APP办理国际漫游功能，我也可以继续协助您查询办理条件。'},summary:['国际漫游功能咨询','咨询国际漫游开通方式','已开始查询国际漫游办理方式','根据查询结果继续协助用户']}
];
const customerStates=Object.fromEntries(customers.map(c=>[c.number,{messages:c.messages.map(m=>({...m})),recommendations:[{...c.recommendation}],summary:[...c.summary],summaryStatus:'',input:'',pinned:null,revision:0,lastAgentSent:Date.now(),lastSummaryRevision:0,lastAutoSummarySend:null,summaryBusy:false,responseCount:0,pendingReplies:0}]));
let activeCustomerNumber=customers[0].number;
const activeCustomer=()=>customers.find(c=>c.number===activeCustomerNumber);
const activeState=()=>customerStates[activeCustomerNumber];
function renderCustomerTabs(){$('#customerTabs').innerHTML=customers.map(c=>`<button class="customer-tab ${c.number===activeCustomerNumber?'active':''}" data-customer="${c.number}">${c.number}(${c.city})<sup>×</sup></button>`).join('')}
function renderPinned(){const pinned=activeState().pinned,box=$('#chatPinned');box.hidden=!pinned;box.textContent=pinned?`${pinned.role==='customer'?'客户':'客服'}：${pinned.text}`:''}
function renderMessages(){const area=$('#messages'),messages=activeState().messages;area.innerHTML=messages.map((m,i)=>`<div class="message ${m.role}">${m.time?`<time>${esc(m.time)}</time>`:''}<div class="bubble"><span>${esc(m.text)}</span><button class="pin-message" data-pin-message="${i}" title="置顶此消息" aria-label="置顶此消息">📌</button></div></div>`).join('');area.scrollTop=area.scrollHeight}
$('#messages').onclick=e=>{const button=e.target.closest('[data-pin-message]');if(!button)return;const message=activeState().messages[Number(button.dataset.pinMessage)];activeState().pinned={role:message.role,text:message.text};renderPinned();toast('消息已置顶')};
function renderRecommendations(){const area=$('#recommendHistory'),recommendations=activeState().recommendations;area.innerHTML=recommendations.map((r,i)=>`<article class="recommend-item"><time>推荐时间：${esc(r.time)}</time><div class="scenario-name">${esc(r.scene)}</div><div class="recommend-text">${esc(r.text)}</div><div class="recommend-page"><button data-page="${i}">办理页面跳转</button></div><div class="recommend-actions"><button class="secondary" data-fill="${i}">填入输入框</button></div></article>`).join('');area.scrollTop=recommendations.length>1?area.scrollHeight:0}
function fillInput(text){activateTab('im');$('#messageInput').value=text;updateCount();$('#messageInput').focus();toast('话术已填入输入框')}
function updateCount(){$('#count').textContent=$('#messageInput').value.length+'/1000'}$('#messageInput').addEventListener('input',()=>{activeState().input=$('#messageInput').value;updateCount()});$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){if(e.ctrlKey||e.shiftKey){e.preventDefault();const input=e.target,start=input.selectionStart,end=input.selectionEnd;input.setRangeText('\n',start,end,'end');activeState().input=input.value;updateCount()}else{e.preventDefault();sendMessage(inputValue())}}});const inputValue=()=>$('#messageInput').value;
let refreshQueue=Promise.resolve();
function replyFor(text,state){if(/谢谢|再见/.test(text))return {text:'好的，谢谢您的帮助，我知道了。',scene:'通用服务 > 服务结束',recommend:'不客气，很高兴为您服务。如有其他问题，欢迎随时联系我们。'};if(/账单|费用|扣费/.test(text))return {text:'那麻烦您再帮我看一下，本月账单有没有额外扣费？',scene:'费用争议 > 账单费用核查',recommend:'您好，我这边为您核查本月账单及费用明细，请您稍等。您也可以通过账单查询查看具体费用。'};const steps=[{text:'我刚订了一个流量包，为什么还是不能上网呢？',scene:'流量争议 > 达量断网且有新订包',recommend:'您好，您当前有新订购的流量包，我这边为您核查流量包的生效情况及上网状态，请您稍等。'},{text:'好的，那需要我重启手机试一下吗？',scene:'流量争议 > 达量断网且有新订包',recommend:'您好，建议您先开启飞行模式后关闭，或重启手机再尝试上网。如仍无法使用，我这边继续为您核查。'},{text:'现在可以上网了，剩余流量在哪里能查看呢？',scene:'流量争议 > 剩余流量查询',recommend:'您好，您可以在中国电信APP中查询剩余流量，当前剩余27.8GB，建议您留意后续使用情况。'}];return steps[state.responseCount++%steps.length]}
function sendMessage(text){text=text.trim();if(!text){toast('请输入回复内容');return}if(text.length>1000){toast('回复内容不能超过1000字');return}const customerNumber=activeCustomerNumber,state=activeState();state.messages.push({role:'agent',text,time:clock()});state.revision++;state.lastAgentSent=Date.now();renderMessages();$('#messageInput').value='';state.input='';updateCount();const reply=replyFor(text,state);state.pendingReplies++;$('#chatStatus').textContent='对方正在输入…';setTimeout(()=>{state.messages.push({role:'customer',text:reply.text,time:clock()});state.revision++;state.pendingReplies--;if(activeCustomerNumber===customerNumber){$('#chatStatus').textContent=state.pendingReplies?'对方正在输入…':'';renderMessages()}refreshQueue=refreshQueue.then(()=>new Promise(resolve=>{if(activeCustomerNumber===customerNumber)$('#recommendLoading').hidden=false;setTimeout(()=>{state.recommendations.push({time:clock(),scene:reply.scene,intro:'根据客户最新消息，推荐以下回复：',text:reply.recommend});if(activeCustomerNumber===customerNumber){renderRecommendations();$('#recommendLoading').hidden=true}resolve()},1100)}))},1500)}
$('#send').onclick=()=>sendMessage(inputValue());$('#recommendHistory').onclick=e=>{const b=e.target.closest('button');if(!b)return;const recommendations=activeState().recommendations;if(b.dataset.fill!==undefined)fillInput(recommendations[+b.dataset.fill].text);if(b.dataset.page!==undefined)openScene('故障专区')};
function drawSummary(data,persist=true){let text=Array.isArray(data)?data.join('；'):String(data||'');text=text.slice(0,150);if(persist)activeState().summary=text;$('#summaryContent').innerHTML=`<p class="summary-text">${esc(text)}</p>`}
function generateSummary(automatic=false){const customerNumber=activeCustomerNumber,state=activeState();if(state.summaryBusy)return;state.summaryBusy=true;const targetRevision=state.revision,snapshot=state.messages.slice(),sentAt=state.lastAgentSent;$('#generateSummary').disabled=true;$('#generateSummary').innerHTML='<span class="spinner"></span>';$('#summaryStatus').textContent='正在生成会话小结…';setTimeout(()=>{const c=snapshot.filter(x=>x.role==='customer').at(-1),a=snapshot.filter(x=>x.role==='agent').at(-1);const topic=/账单|扣费|费用/.test(c.text)?'账单费用':/不能上网|重启/.test(c.text)?'流量使用及上网问题':'流量使用情况';const follow=/谢谢|知道了/.test(c.text)?'客户已确认处理结果。':'需继续跟进客户反馈并确认问题是否解决。';state.summary=`客户咨询${topic}，主要诉求为“${c.text.length>42?c.text.slice(0,42)+'…':c.text}”。客服已回复“${a.text.length>48?a.text.slice(0,48)+'…':a.text}”。${follow}`.slice(0,150);state.lastSummaryRevision=targetRevision;if(automatic)state.lastAutoSummarySend=sentAt;state.summaryBusy=false;state.summaryStatus=(automatic?'自动更新':'手动更新')+' · '+new Date().toLocaleTimeString('zh-CN',{hour12:false});if(activeCustomerNumber===customerNumber){drawSummary(state.summary,false);$('#generateSummary').disabled=false;$('#generateSummary').textContent='小结生成';$('#summaryStatus').textContent=state.summaryStatus}},850)}$('#generateSummary').onclick=()=>generateSummary();
setInterval(()=>{const state=activeState();if(Date.now()-state.lastAgentSent>=60000&&!state.summaryBusy&&(state.lastAutoSummarySend!==state.lastAgentSent||state.revision>state.lastSummaryRevision))generateSummary(true)},500);
function switchCustomer(number){
 if(number===activeCustomerNumber&&$('#profilePrimary').textContent)return;
 activeState().input=$('#messageInput').value;
 activeCustomerNumber=number;
 const customer=activeCustomer(),state=activeState();
 $('#customerRegion').innerHTML=`<option>${esc(customer.region)}</option>`;
 $('#customerNumberInput').value=customer.number;
 $('#samePackage').innerHTML=`<option>${esc(customer.number)}</option>`;
 $('#profilePrimary').textContent=`${customer.name}　 ${customer.number}`;
 $('#profileLocation').textContent=`归属地：${customer.location}`;
 $('#profileName').textContent=`用户姓名：${customer.name}`;
 $('#userSession').textContent=customer.session;
 $('#userIm').textContent=customer.im;
 $('#userLocation').textContent=customer.city;
 $('#chatAvatar').textContent=customer.avatar;
 $('#chatCustomerName').textContent=customer.salutation;
 $('#messageInput').value=state.input;
 $('#chatStatus').textContent=state.pendingReplies?'对方正在输入…':'';
 $('#summaryStatus').textContent=state.summaryStatus;
 $('#generateSummary').disabled=state.summaryBusy;
 $('#generateSummary').innerHTML=state.summaryBusy?'<span class="spinner"></span>':'小结生成';
 $('#recommendLoading').hidden=true;
 renderCustomerTabs();renderMessages();renderPinned();renderRecommendations();drawSummary(state.summary,false);updateCount();activateTab('im');
}
$('#customerTabs').onclick=e=>{const tab=e.target.closest('[data-customer]');if(tab)switchCustomer(tab.dataset.customer)};
const sceneNames=['国际漫游功能','国际漫游使用方法','充值缴费','查询套餐剩余量','返费查询','查询话费','账单查询','详单查询','积分兑换记录','积分有效期','号码状态查询','积分查询','套餐资费','国际漫游资费标准','套餐变更','增值业务查询','家长控制','PUK码','PIN码','【充值】充值错误','黑名单','渠道接触历史查询','携号转网历史查询','10000号与宽带查询','数字增值包查询','智能客服查询'];let activeScene='';
function renderScenes(){const q=$('#sceneSearch').value.trim();$('#sceneTree').innerHTML='<details open><summary> 查询</summary>'+sceneNames.filter(n=>n.includes(q)).map(n=>`<button class="scene-item ${activeScene===n?'active':''}" data-scene="${esc(n)}">${esc(n)}</button>`).join('')+'</details>'}renderScenes();$('#sceneSearch').oninput=renderScenes;$('#sceneTree').onclick=e=>{const b=e.target.closest('[data-scene]');if(b)openScene(b.dataset.scene)};
let scenePanelState='narrow';
function setScenePanelState(state){scenePanelState=state;const side=$('#sceneSide'),lower=$('.workspace-lower'),widthToggle=$('#sceneWidthToggle'),widthArrow=$('#sceneWidthArrow'),widthText=$('#sceneWidthText'),visibilityToggle=$('#sceneVisibilityToggle');side.hidden=state==='hidden';widthToggle.hidden=state==='hidden';lower.dataset.sceneState=state;if(state==='hidden'){visibilityToggle.textContent='《';visibilityToggle.title='显示场景树';visibilityToggle.setAttribute('aria-label','显示场景树');return}side.dataset.sceneState=state;visibilityToggle.textContent='》';visibilityToggle.title='隐藏场景树';visibilityToggle.setAttribute('aria-label','隐藏场景树');const narrow=state==='narrow';widthArrow.textContent=narrow?'《':'》';widthText.textContent=narrow?'展开':'收窄';widthToggle.title=narrow?'展开场景树':'收窄场景树';widthToggle.setAttribute('aria-label',widthToggle.title)}
$('#sceneWidthToggle').onclick=()=>setScenePanelState(scenePanelState==='narrow'?'expanded':'narrow');
$('#sceneVisibilityToggle').onclick=()=>setScenePanelState(scenePanelState==='hidden'?'narrow':'hidden');
setScenePanelState('narrow');
let currentTab='im';const tabs=[];function renderTabs(){$('#workTabs').innerHTML=`<button class="work-tab ${currentTab==='im'?'active':''}" data-tab="im">IM聊天</button>`+tabs.map(n=>`<button class="work-tab ${currentTab===n?'active':''}" data-tab="${esc(n)}">${esc(n)}<span class="close-tab" data-close="${esc(n)}" role="button" aria-label="关闭${esc(n)}" tabindex="0">×</span></button>`).join('')}
function activateTab(id){currentTab=id;$('#imView').hidden=id!=='im';$('#sceneView').hidden=id==='im';activeScene=id==='im'?'':id;renderTabs();renderScenes()}
function openScene(name){if(!tabs.includes(name))tabs.push(name);$('#sceneView').innerHTML=billingMarkup();activateTab(name)}function closeTab(name){const index=tabs.indexOf(name);tabs.splice(index,1);if(currentTab===name)activateTab(tabs[index-1]||tabs[index]||'im');else renderTabs()}
$('#workTabs').onclick=e=>{const c=e.target.closest('[data-close]');if(c){closeTab(c.dataset.close);return}const t=e.target.closest('[data-tab]');if(t)activateTab(t.dataset.tab)};$('#workTabs').onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.close){e.preventDefault();closeTab(e.target.dataset.close)}};renderTabs();
function billingMarkup(){const customer=activeCustomer(),vals=[211.10,223.60,219.40,219.30,219.10,227.50];return `<div class="billing"><div class="bill-left"><h2>本月消费：211.10元</h2><p>（实时费用仅供参考，请以月末结账后账单为准）</p><div class="bill-city">□ 迁号 ${esc(customer.city)}市</div><table class="bill-table"><tbody><tr class="group"><td colspan="4">融合畅享189套餐(不含零)　⌄</td></tr><tr class="group"><td>${esc(customer.number)}</td><th>原价</th><th>减免</th><th>消费</th></tr><tr><td colspan="4">套餐外通信费 ⓘ</td></tr><tr><td class="plan">国内短信费</td><td>0.10</td><td>0.00</td><td>0.10</td></tr><tr><td class="plan">国内短信费</td><td>1.90</td><td>0.00</td><td>1.90</td></tr><tr><td colspan="4">综合信息服务费 ⓘ</td></tr><tr><td class="plan">生活权益随用（2024）</td><td>0.10</td><td>0.00</td><td>0.10</td></tr><tr><td class="plan">量子密话月功能费</td><td>15.00</td><td>-15.00</td><td>0.00</td></tr><tr><td style="text-align:right">小计</td><td>17.10</td><td>-15.00</td><td>2.10</td></tr>${['193****0886','189****1932','189****8921','181****8543'].map(n=>`<tr class="group"><td>${n}</td><th>原价</th><th>减免</th><th>消费</th></tr><tr><td colspan="4">套餐及固定费 ⓘ</td></tr><tr><td class="plan">我的e家可选包</td><td>10.00</td><td>-10.00</td><td>0.00</td></tr><tr><td style="text-align:right">小计</td><td>10.00</td><td>-10.00</td><td>0.00</td></tr>`).join('')}</tbody></table></div><div class="bill-right"><div class="bill-shortcuts">${['账务专区','可选包专区','服务变更','增值专区','靓号明细'].map(x=>`<button data-bill-action="${x}">${x}</button>`).join('')}</div><div class="chart-label">费用分析<button id="billCompare">对比账单</button></div><div class="bill-chart">${vals.map((v,i)=>`<div class="bar" style="--height:${v/3}px"><span>${v.toFixed(2)}</span><small>20260${9-i}</small></div>`).join('')}</div><div>新增费用诊断：对比上个账期新增 <em>0.10元</em>，有以下费用新增</div><table class="bill-detail"><tr><th>号码</th><th>项目项</th><th>金额</th></tr><tr><td>${esc(customer.number)}</td><td>国内短信费</td><td>0.10</td></tr></table></div></div>`}
$('#sceneView').onclick=e=>{if(e.target.closest('[data-bill-action]'))toast('当前展示账单查询页面');if(e.target.id==='billCompare')toast('已展示近六个月账单对比')};
const initialPhrases=[{id:'p1',group:'通用话术',category:'开场问候',text:'您好，很高兴为您服务，请问有什么可以帮您？'},{id:'p2',group:'通用话术',category:'结束用语',text:'感谢您的咨询，祝您生活愉快，再见！'},{id:'p3',group:'业务话术',category:'流量争议',text:'您好，我这边为您核查当前的流量使用情况，请您稍等。'},{id:'p4',group:'业务话术',category:'费用争议',text:'您好，我这边为您查询本月账单和费用明细，请您稍等。'}];
let phrases;try{const stored=JSON.parse(localStorage.getItem('online-assistant-phrases-v1'));phrases=Array.isArray(stored)&&stored.every(p=>p&&['id','group','category','text'].every(k=>typeof p[k]==='string'))?stored:initialPhrases.slice()}catch{phrases=initialPhrases.slice()}
const canManagePhrase=p=>p&&p.group!=='通用话术';
let classifications=[];try{const saved=JSON.parse(localStorage.getItem('online-assistant-categories-v1'));if(Array.isArray(saved))classifications=saved.filter(x=>x&&typeof x.name==='string'&&Array.isArray(x.children)).map(x=>({name:x.name,children:x.children.filter(c=>typeof c==='string')}))}catch{}
for(const p of [...initialPhrases,...phrases]){let g=classifications.find(g=>g.name===p.group);if(!g){g={name:p.group,children:[]};classifications.push(g)}if(!g.children.includes(p.category))g.children.push(p.category)}
function saveClassifications(){try{localStorage.setItem('online-assistant-categories-v1',JSON.stringify(classifications))}catch{toast('分类已在本页保存')}}
function savePhrases(){try{localStorage.setItem('online-assistant-phrases-v1',JSON.stringify(phrases))}catch{toast('浏览器未允许保存，话术将在本次页面内保留')}}
const phrasePrimaryGroups=['通用话术','业务话术'],phraseGroupLabels={'通用话术':'公共','业务话术':'私人'};
let selectedPhrase='p1',editingId=null,activePhraseGroup='通用话术',activePhraseCategory='开场问候';const openGroups=new Set(['通用话术','业务话术','通用话术/开场问候']);
function renderPhrases(){const q=$('#phraseSearch').value.trim().toLowerCase(),group=classifications.find(g=>g.name===activePhraseGroup)||{children:[]};if(!group.children.includes(activePhraseCategory))activePhraseCategory=group.children[0]||'';const list=phrases.filter(p=>p.group===activePhraseGroup&&p.category===activePhraseCategory&&(!q||[p.text,p.category].some(v=>v.toLowerCase().includes(q))));$('#addPhrase').hidden=activePhraseGroup==='通用话术';$('#phraseTree').innerHTML=`<div class="phrase-primary-tabs">${phrasePrimaryGroups.map(g=>`<button class="${g===activePhraseGroup?'active':''}" data-phrase-group="${esc(g)}">${phraseGroupLabels[g]}</button>`).join('')}</div><div class="phrase-category-radios">${group.children.map(cat=>`<label><input type="radio" name="phraseCategory" data-phrase-category="${esc(cat)}" ${cat===activePhraseCategory?'checked':''}> ${esc(cat)}</label>`).join('')}</div><div class="phrase-list-head"><span>编号</span><span>回复内容</span></div><div class="phrase-list">${list.map((p,i)=>`<div class="phrase-row ${selectedPhrase===p.id?'selected':''}" data-id="${esc(p.id)}" tabindex="0" title="单击填入：${esc(p.text)}"><span class="phrase-number">${String(i+1).padStart(2,'0')}</span>${editingId===p.id?`<div class="inline-editor"><textarea maxlength="1000" aria-label="编辑话术内容">${esc(p.text)}</textarea><div class="inline-actions"><button class="secondary" data-cancel-edit>取消</button><button data-save-edit>保存</button></div></div>`:`<span class="phrase-text">${esc(p.text)}</span>`}</div>`).join('')||'<div class="empty">暂无匹配话术</div>'}</div>`;if(editingId)$('#phraseTree textarea')?.focus()}
renderPhrases();$('#phraseSearch').oninput=renderPhrases;
$('#phraseTree').onclick=e=>{const groupButton=e.target.closest('[data-phrase-group]');if(groupButton){activePhraseGroup=groupButton.dataset.phraseGroup;activePhraseCategory=classifications.find(g=>g.name===activePhraseGroup)?.children[0]||'';renderPhrases();return}const row=e.target.closest('.phrase-row');if(!row)return;const p=phrases.find(p=>p.id===row.dataset.id);if(e.target.closest('[data-save-edit]')){if(!canManagePhrase(p))return;const value=row.querySelector('textarea').value.trim();if(!value)return toast('话术内容不能为空');p.text=value;editingId=null;savePhrases();renderPhrases();toast('话术已保存');return}if(e.target.closest('[data-cancel-edit]')){editingId=null;renderPhrases();return}if(editingId===p.id)return;selectedPhrase=p.id;renderPhrases();fillInput(p.text)};
$('#phraseTree').onchange=e=>{if(e.target.matches('[data-phrase-category]')){activePhraseCategory=e.target.dataset.phraseCategory;renderPhrases()}};
let contextId;$('#phraseTree').oncontextmenu=e=>{const row=e.target.closest('.phrase-row');if(!row||editingId)return;e.preventDefault();if(!canManagePhrase(phrases.find(p=>p.id===row.dataset.id))){$('#contextMenu').hidden=true;return}contextId=row.dataset.id;const menu=$('#contextMenu');menu.hidden=false;menu.style.left=Math.min(e.clientX,innerWidth-125)+'px';menu.style.top=Math.min(e.clientY,innerHeight-90)+'px'};document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('#contextMenu').hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#contextMenu').hidden=true});
let modalSubmit=null;function showModal(title,body,onSubmit,confirm='确定'){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#confirmModal').textContent=confirm;modalSubmit=onSubmit;$('#modal').showModal()}$('#cancelModal').onclick=()=>$('#modal').close();$('#modalForm').onsubmit=e=>{e.preventDefault();if(modalSubmit()!==false)$('#modal').close()};
$('#contextMenu').onclick=e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;$('#contextMenu').hidden=true;const p=phrases.find(p=>p.id===contextId);if(!canManagePhrase(p))return;if(action==='edit'){editingId=p.id;renderPhrases()}else showModal('删除话术',`<p>确定删除这条话术吗？删除后将无法恢复。</p><p style="color:#7b8799;line-height:1.7">${esc(p.text)}</p>`,()=>{phrases=phrases.filter(x=>x.id!==p.id);savePhrases();renderPhrases();toast('话术已删除')},'删除')};
function categoryOptions(items,selected){return items.map(n=>`<option value="${esc(n)}" ${n===selected?'selected':''}>${esc(n)}</option>`).join('')}
function refreshCategorySelects(group,category){$('#newGroup').value='业务话术';const selected=classifications.find(g=>g.name==='业务话术');$('#newCategory').innerHTML='<option value="">请选择二级分类</option>'+categoryOptions(selected?.children||[],category)}
function beginCategory(level){const box=$('#categoryCreator');box.hidden=false;box.dataset.level=level;$('#categoryName').value='';$('#categoryName').placeholder=level===1?'请输入新的一级分类名称':'请输入新的二级分类名称';$('#categoryCaption').textContent=level===1?'新增一级分类':'新增二级分类 · '+$('#newGroup').value;$('#categoryName').focus()}
$('#addPhrase').onclick=()=>{
showModal('新增私人话术',`<label>一级分类<div class="locked-category">私人话术</div><input type="hidden" id="newGroup" value="业务话术"></label><label>二级分类<div class="category-control"><select id="newCategory" required aria-label="二级分类"></select><button type="button" id="addCategory" class="secondary">＋ 新增</button></div></label><div id="categoryCreator" hidden><b id="categoryCaption"></b><input id="categoryName" maxlength="30"><div class="category-actions"><button type="button" class="secondary" id="cancelCategory">取消</button><button type="button" id="saveCategory">保存分类</button></div><small id="categoryError" role="alert"></small></div><label>话术内容<textarea id="newText" placeholder="请输入话术内容" required maxlength="1000"></textarea></label>`,()=>{
if(!$('#categoryCreator').hidden){$('#categoryError').textContent='请先保存或取消正在新增的分类';return false}
const group=$('#newGroup').value,category=$('#newCategory').value,text=$('#newText').value.trim();if(!group||!category||!text){toast('请完整填写分类和话术内容');return false}const id='p'+Date.now();phrases.push({id,group,category,text});openGroups.add(group);openGroups.add(group+'/'+category);activePhraseGroup=group;activePhraseCategory=category;selectedPhrase=id;$('#phraseSearch').value='';savePhrases();renderPhrases();toast('话术已新增')},'保存');
refreshCategorySelects('业务话术','流量争议');
$('#addCategory').onclick=()=>{beginCategory(2);$('#categoryError').textContent=''};
$('#cancelCategory').onclick=()=>$('#categoryCreator').hidden=true;
$('#saveCategory').onclick=()=>{const name=$('#categoryName').value.trim(),group=classifications.find(g=>g.name===$('#newGroup').value);const fail=t=>$('#categoryError').textContent=t;if(!name)return fail('分类名称不能为空');if(!group)return fail('请先选择一级分类');if(group.children.includes(name))return fail('当前一级分类下已存在同名二级分类');group.children.push(name);openGroups.add(group.name+'/'+name);activePhraseGroup=group.name;activePhraseCategory=name;refreshCategorySelects(group.name,name);saveClassifications();renderPhrases();$('#categoryCreator').hidden=true;toast('分类已新增')};
$('#categoryName').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('#saveCategory').click()}};
};
$('#collapse').onclick=()=>{const d=$('#profileDetails');d.hidden=!d.hidden;$('#collapse').textContent=d.hidden?'展开客户详情⌄':'收起客户详情⌃'};
document.querySelectorAll('[data-resize-panel]').forEach(resizer=>{let startX=0,startWidth=0,baseWidth=0;const panel=$('#'+resizer.dataset.resizePanel);resizer.onpointerdown=e=>{startX=e.clientX;startWidth=panel.getBoundingClientRect().width;baseWidth=Number(panel.dataset.baseWidth)||startWidth;panel.dataset.baseWidth=baseWidth;resizer.setPointerCapture(e.pointerId);document.body.classList.add('resizing-assistant')};resizer.onpointermove=e=>{if(!resizer.hasPointerCapture(e.pointerId))return;const otherWidth=[...document.querySelectorAll('#imView>.phrase-column,#imView>.assistant')].filter(x=>x!==panel).reduce((sum,x)=>sum+x.getBoundingClientRect().width,0),maxWidth=Math.min(baseWidth*2,$('#imView').clientWidth-otherWidth-298),next=Math.max(baseWidth,Math.min(maxWidth,startWidth+startX-e.clientX));panel.style.width=next+'px';panel.style.flex='0 0 '+next+'px'};resizer.onpointerup=e=>{if(resizer.hasPointerCapture(e.pointerId))resizer.releasePointerCapture(e.pointerId);document.body.classList.remove('resizing-assistant')};resizer.ondblclick=()=>{panel.style.width='';panel.style.flex='';delete panel.dataset.baseWidth;toast('已恢复默认宽度')}});
$('#query').onclick=()=>{const number=$('#customerNumberInput').value.trim(),matched=customers.find(c=>c.number===number);if(!matched)return toast('未找到对应客户页签');switchCustomer(matched.number);toast(`已切换至${matched.salutation}的客户页面`)};
switchCustomer(customers[0].number);
